// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMYSgmBk2R_hPBIO59b9_gMNG15sAONUs',
    appId: '1:214251261945:web:cd11172bbe397a7bcab728',
    messagingSenderId: '214251261945',
    projectId: 'kema-5963c',
    authDomain: 'kema-5963c.firebaseapp.com',
    storageBucket: 'kema-5963c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkAGXncHhGyq9Ml4-du-_7MtrqsCv0BJM',
    appId: '1:214251261945:android:f6f585ffda23531dcab728',
    messagingSenderId: '214251261945',
    projectId: 'kema-5963c',
    storageBucket: 'kema-5963c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6v5pCPQbZyM8X6z6Be8TsDP-J6BCGtDU',
    appId: '1:214251261945:ios:56a52e1e3521a35dcab728',
    messagingSenderId: '214251261945',
    projectId: 'kema-5963c',
    storageBucket: 'kema-5963c.firebasestorage.app',
    iosBundleId: 'com.example.splachWithLoginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6v5pCPQbZyM8X6z6Be8TsDP-J6BCGtDU',
    appId: '1:214251261945:ios:56a52e1e3521a35dcab728',
    messagingSenderId: '214251261945',
    projectId: 'kema-5963c',
    storageBucket: 'kema-5963c.firebasestorage.app',
    iosBundleId: 'com.example.splachWithLoginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMYSgmBk2R_hPBIO59b9_gMNG15sAONUs',
    appId: '1:214251261945:web:28b624018fb5c282cab728',
    messagingSenderId: '214251261945',
    projectId: 'kema-5963c',
    authDomain: 'kema-5963c.firebaseapp.com',
    storageBucket: 'kema-5963c.firebasestorage.app',
  );
}
